# Generated by Django 4.1 on 2022-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
